// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("ovirt");

/**
 * Additional headers to be added to each API call
 */
export let headers: {[key: string]: string} | undefined = __config.getObject<{[key: string]: string}>("headers");
/**
 * Login password
 */
export let password: string | undefined = __config.get("password");
/**
 * Ovirt server url
 */
export let url: string | undefined = __config.get("url");
/**
 * Login username
 */
export let username: string | undefined = __config.get("username");
