# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union
from .. import _utilities, _tables

__all__ = [
    'headers',
    'password',
    'url',
    'username',
]

__config__ = pulumi.Config('ovirt')

headers = __config__.get('headers')
"""
Additional headers to be added to each API call
"""

password = __config__.get('password')
"""
Login password
"""

url = __config__.get('url')
"""
Ovirt server url
"""

username = __config__.get('username')
"""
Login username
"""

