// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi/config"
)

// Additional headers to be added to each API call
func GetHeaders(ctx *pulumi.Context) string {
	return config.Get(ctx, "ovirt:headers")
}

// Login password
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "ovirt:password")
}

// Ovirt server url
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "ovirt:url")
}

// Login username
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "ovirt:username")
}
